use_frameworks!

target 'SSCodeView_Example' do
  pod 'SSCodeView', :path => '../'

  target 'SSCodeView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
