#Default Source for Cocoapods
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Uncomment this line to define a global platform for your project
platform :ios, "9.0"


def universal_pods
end

def core_pod
	pod 'SSCodeView', :path => '../'
end

def test_pods
	pod 'Quick', '~> 1.0.0'
	pod 'Nimble', '~> 5.1.1'
end

target 'SSCodeView_Example' do
	universal_pods
	core_pod
end

target 'SSCodeView_Tests' do
	universal_pods
	core_pod
	test_pods
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '3.0'
		end
	end
end
